version: "3.8"

services:
  user-db:
    image: postgres:15-alpine
    container_name: userdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - user_db_data:/var/lib/postgresql/data 
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog-db:
    image: postgres:15-alpine
    container_name: catalog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog_db
    ports:
      - "5433:5432"
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d catalog_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  session-db:
    image: postgres:15-alpine
    container_name: session_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: session_db
    ports:
      - "5435:5432"
    volumes:
      - session_postgres_data:/var/lib/postgresql/data   
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # App communication port
      - "15672:15672" # Management UI port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: web_client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      # Mapeia a pasta local para dentro do container (HOT RELOAD)
      - ./web-client:/app
      # Evita que o node_modules do container seja sobrescrito pelo local
      - /app/node_modules
    # Garante que o front só suba se os bancos estiverem ok (opcional, mas boa prática)
    depends_on:
      - user-db
      - catalog-db

volumes:
  user_db_data:
    driver: local
  catalog_db_data:
    driver: local
  session_postgres_data:
    driver: local