version: '3.8'

services:
  # --- BANCO DE DADOS (SESSION SERVICE) ---
  session-db:
    image: postgres:15-alpine
    container_name: session_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: session_db
    ports:
      - "5433:5432"
    volumes:
      - session_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta de comunicação (TCP)
      - "15672:15672" # Dashboard Web (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  session_postgres_data: